---
name: "wait-for-status-checks"
description: >-
  GitHub Action for wait for status API's result.
  Pass or Fail based on allowed-conclusion.

branding:
  icon: check-circle
  color: green

inputs:
  ref:
    description: >-
      github commit head ref.
    required: true
    default: ${{ github.head_ref }}
  context:
    description: >-
      context string to filter the statuses api.
    required: true
  wait-interval:
    description: >-
      Time to wait between polling (in seconds).
    required: false
    default: 300
  count:
    description: >-
      Number of times to poll before timing out.
    required: false
    default: 12

outputs:
  result:
    description: Failure or success result of the status
    value: ${{ steps.outcome.outputs.result }}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        python3 -m wait-for-status-checks \
          --ref="${{ inputs.ref }}" \
          --context="${{ inputs.context }}" \
          --wait-interval="${{ inputs.wait-interval }}" \
          --count="${{ inputs.count }}" \
